modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="blahmod"
version="1.0.0"
displayName="BlahMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="blahblahbal"

[[dependencies.blahmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




